// ════════════════════════════════════════════════════════════════════
// src/data.js — Static master data (immutable)
// ════════════════════════════════════════════════════════════════════

export const DEFAULT_PACK_COSTS = { l:350, c:925, e:4125, i:4730, mw:4730, sec:4730, avd:0 };

export const PACK_LICENSES = [
  {id:'m365bp',name:'Microsoft 365 Business Premium (no Teams)',cat:'Microsoft 365',type:'Users',l:5,c:15,e:35,i:null,n26:false,n25:false,cpu:264,note:'EEA/RoW edition',mw:25,sec:12,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'teams',name:'Teams Enterprise',cat:'Microsoft 365',type:'Users',l:5,c:15,e:35,i:100,n26:false,n25:false,cpu:63,note:'$5.25/mo × 12',mw:225,sec:112,avd:30,mwspec:50,secspec:50,azcore:true},
  {id:'teamsprem',name:'Teams Premium',cat:'Microsoft 365',type:'Users',l:null,c:null,e:10,i:null,n26:true,n25:false,cpu:84,note:'$7/mo × 12',mw:25,sec:null,avd:null,mwspec:30,secspec:null,azcore:false},
  {id:'roomspro',name:'Teams Rooms Pro',cat:'Microsoft 365',type:'Users',l:null,c:null,e:2,i:null,n26:false,n25:true,cpu:600,note:'$50/mo × 12',mw:5,sec:null,avd:null,mwspec:20,secspec:null,azcore:false},
  {id:'viva',name:'Viva Suite',cat:'Microsoft 365',type:'Users',l:null,c:null,e:15,i:null,n26:false,n25:true,cpu:144,note:'$12/mo × 12',mw:50,sec:null,avd:null,mwspec:50,secspec:null,azcore:false},
  {id:'proj',name:'Project Online – Project Plan 5',cat:'Microsoft 365',type:'Users',l:1,c:5,e:5,i:20,n26:false,n25:false,cpu:552,note:'$46/mo × 12',mw:20,sec:20,avd:null,mwspec:null,secspec:null,azcore:true},
  {id:'visio',name:'Visio Online – Visio Plan 2',cat:'Microsoft 365',type:'Users',l:1,c:5,e:5,i:5,n26:false,n25:false,cpu:180,note:'$15/mo × 12',mw:5,sec:5,avd:null,mwspec:null,secspec:null,azcore:true},
  {id:'win365',name:'Windows 365 Enterprise 8vCPU/32GB/512GB',cat:'Windows',type:'Users',l:null,c:1,e:2,i:null,n26:false,n25:true,cpu:480,note:'$40/mo × 12',mw:5,sec:2,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'m365cop',name:'Microsoft 365 Copilot',cat:'Copilot',type:'Users',l:null,c:null,e:10,i:null,n26:true,n25:false,cpu:360,note:'$30/mo × 12',mw:20,sec:null,avd:null,mwspec:20,secspec:5,azcore:false},
  {id:'copstudio',name:'Microsoft Copilot Studio (25k credits/mo)',cat:'Copilot',type:'Pack/mo',l:null,c:null,e:1,i:null,n26:true,n25:false,cpu:200,note:'25k Copilot credits/mo',mw:1,sec:null,avd:null,mwspec:2,secspec:null,azcore:false},
  {id:'dragon',name:'Microsoft Dragon Copilot',cat:'Copilot',type:'Users',l:null,c:5,e:15,i:20,n26:true,n25:false,cpu:480,note:'Healthcare AI',mw:20,sec:20,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'azurecr',name:'Azure Bulk Credits (Production)',cat:'Azure',type:'USD/yr',l:700,c:2400,e:5000,i:10000,n26:false,n25:false,cpu:1,note:'Production Azure credits',mw:4000,sec:10000,avd:14000,mwspec:6000,secspec:10000,azcore:false},
  {id:'ghcop',name:'GitHub Copilot Enterprise (via Azure credits)',cat:'Copilot',type:'USD/yr',l:null,c:null,e:null,i:5000,n26:true,n25:false,cpu:1,note:'$5k Azure credits for GH Copilot',mw:null,sec:null,avd:10000,mwspec:null,secspec:null,azcore:false},
  {id:'entraid',name:'Entra ID P2',cat:'Security',type:'Users',l:5,c:15,e:35,i:100,n26:false,n25:true,cpu:144,note:'$12/mo × 12',mw:null,sec:null,avd:30,mwspec:null,secspec:null,azcore:true},
  {id:'defsuit',name:'Defender Suite',cat:'Security',type:'Users',l:5,c:15,e:35,i:100,n26:true,n25:false,cpu:360,note:'Full Defender suite; NEW 2026',mw:25,sec:12,avd:30,mwspec:null,secspec:null,azcore:true},
  {id:'defp2',name:'Defender for Endpoint P2',cat:'Security',type:'Users',l:5,c:15,e:35,i:100,n26:false,n25:true,cpu:84,note:'$7/mo × 12',mw:null,sec:null,avd:30,mwspec:null,secspec:null,azcore:true},
  {id:'entrasuite',name:'Entra Suite',cat:'Security',type:'Users',l:null,c:null,e:35,i:null,n26:true,n25:false,cpu:144,note:'$12/mo × 12',mw:50,sec:50,avd:null,mwspec:25,secspec:25,azcore:false},
  {id:'intune',name:'Intune Suite',cat:'Security',type:'Users',l:null,c:null,e:35,i:null,n26:true,n25:false,cpu:144,note:'$12/mo × 12',mw:50,sec:50,avd:null,mwspec:25,secspec:25,azcore:false},
  {id:'vsent',name:'Visual Studio Enterprise IDE',cat:'Dev Tools',type:'Users',l:1,c:8,e:15,i:25,n26:true,n25:false,cpu:2999,note:'~$249.92/mo × 12',mw:25,sec:25,avd:25,mwspec:10,secspec:10,azcore:false},
  {id:'pbiprem',name:'Power BI Premium (per user)',cat:'Power Platform',type:'Users',l:4,c:15,e:35,i:100,n26:false,n25:false,cpu:240,note:'$20/mo × 12',mw:null,sec:null,avd:null,mwspec:null,secspec:null,azcore:true},
  {id:'powerapps',name:'Power Apps Premium',cat:'Power Platform',type:'Users',l:1,c:8,e:15,i:25,n26:false,n25:false,cpu:240,note:'$20/mo × 12',mw:25,sec:25,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'paauto',name:'Power Automate Premium',cat:'Power Platform',type:'Users',l:1,c:8,e:15,i:25,n26:false,n25:false,cpu:180,note:'$15/mo × 12',mw:25,sec:25,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'paaproc',name:'Power Automate Process',cat:'Power Platform',type:'Bots',l:null,c:null,e:2,i:5,n26:false,n25:false,cpu:1800,note:'$150/mo × 12 per bot',mw:5,sec:5,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'d365bc',name:'Dynamics 365 Business Central Premium',cat:'Dynamics 365',type:'Users',l:4,c:15,e:35,i:null,n26:false,n25:false,cpu:1140,note:'$95/mo × 12',mw:null,sec:null,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'d365se',name:'Dynamics 365 Sales Enterprise',cat:'Dynamics 365',type:'Users',l:4,c:15,e:35,i:null,n26:false,n25:false,cpu:1140,note:'$95/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365ci',name:'Dynamics 365 Customer Insights',cat:'Dynamics 365',type:'Tenant',l:null,c:null,e:1,i:null,n26:false,n25:false,cpu:17400,note:'$1,450/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365cse',name:'Dynamics 365 Customer Service Enterprise',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:1140,note:'$95/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365fp',name:'Dynamics 365 Finance Premium',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:2280,note:'$190/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365hr',name:'Dynamics 365 Human Resources',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:1140,note:'$95/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365mk',name:'Dynamics 365 Marketing (Base Pack)',cat:'Dynamics 365',type:'Tenant',l:null,c:null,e:1,i:null,n26:false,n25:true,cpu:18000,note:'$1,500/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365po',name:'Dynamics 365 Project Operations',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:1380,note:'$115/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365tm',name:'Dynamics 365 Team Members',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:120,note:'$10/mo × 12',mw:null,sec:null,avd:null},
  {id:'d365cc',name:'Dynamics 365 Contact Center',cat:'Dynamics 365',type:'Users',l:null,c:null,e:35,i:null,n26:false,n25:true,cpu:1140,note:'$95/mo × 12',mw:35,sec:null,avd:null,mwspec:25,secspec:null,azcore:false},
  {id:'wsrvstd',name:'Windows Server Standard – Per core (2025)',cat:'Windows Server',type:'Licenses',l:null,c:16,e:32,i:100,n26:false,n25:true,cpu:97,note:'~$97/core/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'wsrvdc',name:'Windows Server Datacenter – Per core (2025)',cat:'Windows Server',type:'Licenses',l:null,c:16,e:32,i:32,n26:false,n25:true,cpu:433,note:'~$433/core/yr',mw:32,sec:32,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'wsrvcal',name:'Windows Server CALs (2025)',cat:'Windows Server',type:'Licenses',l:null,c:16,e:35,i:100,n26:false,n25:true,cpu:38,note:'~$38/CAL/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'wsrvrdp',name:'Windows Server RDS CALs (2025)',cat:'Windows Server',type:'Licenses',l:null,c:20,e:35,i:100,n26:false,n25:true,cpu:130,note:'~$130/RDS CAL/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sccms',name:'System Center Client Mgmt Suite (2022)',cat:'Windows Server',type:'Licenses',l:null,c:10,e:35,i:100,n26:false,n25:false,cpu:125,note:'per device/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sccep',name:'System Center Endpoint Protection (2019)',cat:'Windows Server',type:'Licenses',l:null,c:10,e:35,i:100,n26:false,n25:false,cpu:22,note:'per device/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sccstd',name:'System Center Standard (2022)',cat:'Windows Server',type:'Licenses',l:null,c:8,e:16,i:32,n26:false,n25:false,cpu:1069,note:'per 2-proc/yr',mw:32,sec:32,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'epcm',name:'Endpoint Configuration Manager (2019)',cat:'Windows Server',type:'Licenses',l:null,c:null,e:35,i:100,n26:false,n25:false,cpu:125,note:'per device/yr',mw:100,sec:100,avd:null,mwspec:null,secspec:null,azcore:true},
  {id:'sqlent',name:'SQL Server Enterprise – Per core (2019)',cat:'Windows Server',type:'Licenses',l:null,c:null,e:8,i:16,n26:false,n25:false,cpu:3750,note:'~$3,750/core/yr',mw:16,sec:16,avd:null,mwspec:null,secspec:null,azcore:true},
  {id:'m365e3',name:'Microsoft 365 E3 (no Teams)',cat:'Microsoft 365',type:'Users',l:null,c:null,e:null,i:100,n26:false,n25:false,cpu:432,note:'Infra SPD only; $36/mo × 12',mw:null,sec:null,avd:30,mwspec:null,secspec:null,azcore:true},
  {id:'win11iot',name:'Windows 11 IoT Enterprise LTSC',cat:'Windows',type:'Licenses',l:null,c:null,e:null,i:20,n26:false,n25:false,cpu:75,note:'IoT LTSC',mw:20,sec:20,avd:20,mwspec:20,secspec:20,azcore:false},
  {id:'sb-bc',name:'Sandbox – Business Central',cat:'Sandbox',type:'Users',l:5,c:5,e:5,i:null,n26:false,n25:false,cpu:0,note:'Internal sandbox',mw:null,sec:null,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sb-ops',name:'Sandbox – Operations Application',cat:'Sandbox',type:'Users',l:null,c:25,e:25,i:25,n26:false,n25:false,cpu:0,note:'Internal sandbox',mw:25,sec:25,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sb-sfs',name:'Sandbox – Sales, Field Service & CS',cat:'Sandbox',type:'Users',l:null,c:25,e:25,i:25,n26:false,n25:false,cpu:0,note:'Internal sandbox',mw:25,sec:25,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sb-cc',name:'Sandbox – Contact Center',cat:'Sandbox',type:'Users',l:null,c:null,e:25,i:null,n26:false,n25:false,cpu:0,note:'Internal sandbox',mw:null,sec:null,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'sb-t2',name:'Sandbox – Operations Tier 2',cat:'Sandbox',type:'Tenant',l:null,c:1,e:1,i:null,n26:false,n25:false,cpu:0,note:'Internal sandbox',mw:null,sec:null,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'m365e5',name:'Microsoft 365 E5 (no Teams)',cat:'Microsoft 365',type:'Users',l:null,c:null,e:null,i:null,n26:false,n25:false,cpu:684,note:'$57/mo × 12',mw:200,sec:100,avd:null,mwspec:50,secspec:50,azcore:false},
  {id:'m365edu',name:'Microsoft 365 EDU A5',cat:'Microsoft 365',type:'Users',l:null,c:null,e:null,i:null,n26:false,n25:false,cpu:216,note:'Education license',mw:25,sec:12,avd:null,mwspec:null,secspec:null,azcore:false},
  {id:'ghent',name:'GitHub Enterprise Metered (via Azure Credits)',cat:'Dev Tools',type:'USD/yr',l:null,c:null,e:null,i:null,n26:false,n25:false,cpu:1,note:'$2,520 Azure credits for GH Enterprise',mw:null,sec:null,avd:2520,mwspec:null,secspec:null,azcore:false},
  {id:'seccop',name:'Security Copilot (via Azure Credits)',cat:'Copilot',type:'USD/yr',l:null,c:null,e:null,i:null,n26:true,n25:false,cpu:1,note:'Azure credits for Security Copilot',mw:null,sec:5000,avd:null,mwspec:null,secspec:10000,azcore:false},
  {id:'win11e24h2',name:'Windows 11 Enterprise 24H2',cat:'Windows',type:'Licenses',l:null,c:null,e:null,i:null,n26:false,n25:true,cpu:75,note:'Per license',mw:50,sec:50,avd:50,mwspec:50,secspec:50,azcore:false},
  {id:'win11en24h2',name:'Windows 11 Enterprise N 24H2',cat:'Windows',type:'Licenses',l:null,c:null,e:null,i:null,n26:false,n25:true,cpu:75,note:'N edition',mw:50,sec:50,avd:50,mwspec:50,secspec:50,azcore:false},
  {id:'win11eltsc',name:'Windows 11 Enterprise LTSC',cat:'Windows',type:'Licenses',l:null,c:null,e:null,i:null,n26:false,n25:true,cpu:75,note:'LTSC edition',mw:50,sec:50,avd:50,mwspec:50,secspec:50,azcore:false},
  {id:'win11enltsc',name:'Windows 11 Enterprise N LTSC',cat:'Windows',type:'Licenses',l:null,c:null,e:null,i:null,n26:false,n25:true,cpu:75,note:'N LTSC edition',mw:50,sec:50,avd:50,mwspec:50,secspec:50,azcore:false},
  {id:'winstorage',name:'Windows Storage Server Workgroup (2016)',cat:'Windows Server',type:'Licenses',l:null,c:null,e:null,i:2,n26:false,n25:false,cpu:285,note:'~$285/yr',mw:2,sec:2,avd:null,mwspec:null,secspec:null,azcore:false}
];

// ── SKU Lookup Table — Microsoft product name → SKU code + friendly name
// Used for CSV import auto-mapping. "Check for updates" button can refresh this.
// Source: https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference

export const SKU_LOOKUP = [
  // Microsoft 365
  { sku: "SPB",                        name: "Microsoft 365 Business Premium",           price_usd: 22.00 },
  { sku: "O365_BUSINESS_PREMIUM",      name: "Microsoft 365 Business Standard",          price_usd: 12.50 },
  { sku: "O365_BUSINESS_ESSENTIALS",   name: "Microsoft 365 Business Basic",             price_usd:  6.00 },
  { sku: "O365_BUSINESS",              name: "Microsoft 365 Apps for Business",          price_usd:  8.25 },
  { sku: "SPE_E3",                     name: "Microsoft 365 E3",                         price_usd: 36.00 },
  { sku: "SPE_E3_NOPSTNCONF_EEA",      name: "Microsoft 365 E3 EEA (no Teams)",          price_usd: 36.00 },
  { sku: "SPE_E5",                     name: "Microsoft 365 E5",                         price_usd: 57.00 },
  { sku: "O365_BUSINESS_ESSENTIALS_EEA", name: "Microsoft 365 Business Basic EEA",      price_usd:  6.00 },
  { sku: "O365_BUSINESS_PREMIUM_EEA",  name: "Microsoft 365 Business Standard EEA",     price_usd: 12.50 },
  { sku: "SPB_EEA",                    name: "Microsoft 365 Business Premium EEA",       price_usd: 22.00 },
  { sku: "MCOPSTNC",                   name: "Microsoft 365 Copilot",                    price_usd: 30.00 },
  { sku: "M365EDU_A5_FACULTY",         name: "Microsoft 365 EDU A5 Faculty",             price_usd: 18.00 },
  { sku: "M365EDU_A5_STUDENT",         name: "Microsoft 365 EDU A5 Student",             price_usd:  2.50 },

  // Office 365
  { sku: "ENTERPRISEPREMIUM",          name: "Office 365 E5",                            price_usd: 38.00 },
  { sku: "ENTERPRISEPACK",             name: "Office 365 E3",                            price_usd: 23.00 },
  { sku: "STANDARDPACK",               name: "Office 365 E1",                            price_usd: 10.00 },

  // Teams
  { sku: "TEAMS_EEA",                  name: "Microsoft Teams EEA",                      price_usd:  5.25 },
  { sku: "TEAMS1",                     name: "Microsoft Teams Essentials",               price_usd:  4.00 },
  { sku: "TEAMSPREM",                  name: "Teams Premium",                            price_usd:  7.00 },
  { sku: "MCOMEETROOM",                name: "Microsoft Teams Rooms Pro",                price_usd: 40.00 },
  { sku: "MCOMEETBASIC",               name: "Microsoft Teams Rooms Basic",              price_usd:  0.00 },

  // Exchange
  { sku: "EXCHANGESTANDARD",           name: "Exchange Online (Plan 1)",                 price_usd:  4.00 },
  { sku: "EXCHANGEENTERPRISE",         name: "Exchange Online (Plan 2)",                 price_usd:  8.00 },
  { sku: "EXCHANGESTANDARD_GOV",       name: "Exchange Online (Plan 1) GCC",            price_usd:  4.00 },

  // SharePoint / OneDrive
  { sku: "SHAREPOINTSTANDARD",         name: "SharePoint Online (Plan 1)",               price_usd:  5.00 },
  { sku: "SHAREPOINTENTERPRISE",       name: "SharePoint Online (Plan 2)",               price_usd: 10.00 },

  // Power Platform
  { sku: "POWER_BI_PRO",               name: "Power BI Pro",                             price_usd: 10.00 },
  { sku: "POWER_BI_PREMIUM_P1",        name: "Power BI Premium (Per User)",             price_usd: 20.00 },
  { sku: "POWERAPPS_PER_USER",         name: "Power Apps Premium",                       price_usd: 20.00 },
  { sku: "POWERAPPS_DEV",              name: "POWERAPPS_DEV",                            price_usd:  0.00 },
  { sku: "POWERAPPS_VIRAL",            name: "POWERAPPS_VIRAL",                          price_usd:  0.00 },
  { sku: "FLOW_PER_USER",              name: "Power Automate Premium",                   price_usd: 15.00 },
  { sku: "FLOW_PER_USER_2",            name: "Power Automate per user plan",             price_usd: 15.00 },
  { sku: "FLOW_FREE",                  name: "FLOW_FREE (Power Automate Free)",          price_usd:  0.00 },
  { sku: "MICROSOFT_FABRIC_FREE",      name: "Microsoft Fabric (Free)",                  price_usd:  0.00 },
  { sku: "POWER_PAGES_VIRAL",          name: "Power Pages vTrial",                       price_usd:  0.00 },
  { sku: "COPILOTSTUDIO_VIRAL",        name: "Copilot Studio Viral Trial",               price_usd:  0.00 },

  // Project / Planner
  { sku: "PROJECT_P3",                 name: "Project Plan 3",                           price_usd: 30.00 },
  { sku: "PROJECT_P5",                 name: "Planner and Project Plan 5",               price_usd: 55.00 },

  // Visio
  { sku: "VISIOCLIENT",                name: "Visio Plan 2",                             price_usd: 15.00 },
  { sku: "VISIOONLINE_PLAN1",          name: "Visio Plan 1",                             price_usd:  5.00 },

  // Dynamics 365
  { sku: "DYN365_SALES_PROFESSIONAL",  name: "Dynamics 365 Sales Professional",          price_usd: 65.00 },
  { sku: "DYN365_ENTERPRISE_SALES",    name: "Dynamics 365 Sales Enterprise",            price_usd: 95.00 },
  { sku: "DYN365_ENTERPRISE_CUSTOMER_SERVICE", name: "Dynamics 365 Customer Service Enterprise", price_usd: 95.00 },
  { sku: "DYN365_FINANCIALS_BUSINESS_SKU", name: "Dynamics 365 Business Central Premium", price_usd: 100.00 },
  { sku: "DYN365_TEAM_MEMBERS",        name: "Dynamics 365 Team Members",               price_usd: 10.00 },
  { sku: "DYN365_CUSTOMER_INSIGHTS_ATTACH", name: "Dynamics 365 Customer Insights",    price_usd: 1000.00 },

  // Security / Identity
  { sku: "AAD_PREMIUM_P2",             name: "Microsoft Entra ID P2",                    price_usd: 12.00 },
  { sku: "AAD_PREMIUM",                name: "Microsoft Entra ID P1",                    price_usd:  6.00 },
  { sku: "INTUNE_A",                   name: "Microsoft Intune Plan 1",                  price_usd:  8.00 },
  { sku: "WIN_DEF_ATP",                name: "Microsoft Defender for Endpoint P2",       price_usd:  5.20 },

  // Windows
  { sku: "WIN10_VDA_E3",               name: "Windows 10/11 Enterprise E3",              price_usd:  7.00 },
  { sku: "WIN10_VDA_E5",               name: "Windows 10/11 Enterprise E5",              price_usd: 14.00 },

  // Developer
  { sku: "VSENTP",                     name: "Visual Studio Enterprise IDE",             price_usd: 250.00 },
  { sku: "VS_PROFESSIONAL",            name: "Visual Studio Professional",               price_usd:  45.00 },

  // GitHub / Azure
  { sku: "AZURE_CREDITS",              name: "Azure (Production)",                       price_usd:  0.00 },
];

export const I18N = {
  "en": {
    "app_title": "Microsoft Partner Benefits 2026 — License & Financial Tracker",
    "app_sub": "Benefits Guide Feb 18 2026 · sgx-labs.com/partners/microsoft",
    "tag_ms": "Microsoft AI Cloud Partner Program",
    "tag_date": "Feb 2026",
    "tab_licenses": "Licenses",
    "tab_usage": "Usage vs Pack",
    "tab_all": "All Pack Licenses",
    "tab_cloud": "Cloud Rights & Credits",
    "tab_fin1": "Usage Economics",
    "tab_fin2": "Full Pack Value",
    "tab_prices": "Edit Prices",
    "client_select_title": "Select Client",
    "client_new": "New Client",
    "client_name_placeholder": "Client name…",
    "client_create": "Create",
    "client_back": "← Clients",
    "lic_title": "Tenant Licenses",
    "lic_add": "Add License",
    "lic_import_csv": "Import CSV",
    "lic_col_name": "Product",
    "lic_col_sku": "SKU",
    "lic_col_total": "Total",
    "lic_col_assigned": "Assigned",
    "lic_col_price": "Price (USD/mo)",
    "lic_col_actions": "",
    "lic_fetch_prices": "Fetch prices",
    "lic_csv_hint": "Paste CSV with columns: Product Name, Total, Expired, Assigned",
    "lic_csv_import_btn": "Import",
    "lic_csv_cancel": "Cancel",
    "lic_save": "Save",
    "lic_delete_confirm": "Delete this license?",
    "pack_bar_label": "Active packs & multipliers",
    "year": "/ year",
    "instances": "instances",
    "launch_name": "Partner Launch",
    "core_name": "Success Core",
    "exp_name": "Success Expanded",
    "infra_name": "Solutions Partner: Infrastructure",
    "cov_legend": "Coverage:",
    "leg_covered": "Covered",
    "leg_upgrade": "Pack upgrade avail.",
    "leg_needs": "Needs purchase",
    "leg_free": "Free / Trial",
    "show": "Show",
    "all": "All",
    "covered": "Covered",
    "upgrades": "Upgrades",
    "not_covered": "Not Covered",
    "free_trial": "Free/Trial",
    "sort": "Sort",
    "by_coverage": "By Coverage",
    "by_name": "By Name",
    "most_assigned": "Most Assigned",
    "most_needed": "Most Needed",
    "highest_cost": "Highest Cost",
    "stat_skus": "Tenant SKUs",
    "stat_assigned": "Total Assigned",
    "stat_covered": "Covered",
    "stat_upgrades": "Upgrades",
    "stat_needs": "Needs Purchase",
    "stat_over": "Over Pack Limit",
    "col_product": "Tenant Product",
    "col_total": "Total",
    "col_assigned": "Assigned",
    "col_avail": "Total Avail.",
    "col_usage": "Usage vs Pack",
    "col_needed": "Lic. Needed",
    "col_cost": "Cost/Unit/yr",
    "col_coverage": "Coverage",
    "col_edit": "Edit",
    "pill_covered": "Covered",
    "pill_upgrade": "Upgrade Avail.",
    "pill_needs": "Needs Purchase",
    "pill_free": "Free/Trial",
    "pill_over": "Over Limit",
    "sec_covered": "✓  Covered by active partner packs",
    "sec_upgrade": "↑  Pack includes a higher/upgraded edition",
    "sec_uncovered": "✕  Not covered — requires separate purchase",
    "sec_free": "◦  Free / Trial licenses",
    "no_pack_limit": "no pack limit",
    "tab_all_title": "All Pack Licenses",
    "pack_filter": "Pack",
    "category_filter": "Category",
    "new_in": "New in",
    "all_cats": "All Categories",
    "col_license": "License / Product",
    "col_category": "Category",
    "col_type": "Type",
    "col_best_qty": "Best Qty",
    "col_retail": "Retail Value/yr",
    "col_new": "New",
    "stat_pack_lic": "Pack Licenses",
    "stat_retail": "Total Retail Value/yr",
    "stat_invest": "Pack Investment/yr",
    "stat_savings": "Gross Savings/yr",
    "cloud_title": "Cloud Services, Credits & AI Rights",
    "cloud_intro": "<strong>Cloud Services, Credits & AI Rights</strong> — All cloud entitlements, Azure credits, AI service budgets and developer rights included across your active packs. Values shown are the combined total across all instances of active packs. Credits and cloud budgets are for internal use only.",
    "combined_cloud": "Combined Cloud Entitlements Across All Active Packs",
    "azure_credits": "Azure Production Credits",
    "per_year": "Per year across active packs",
    "copilot_credits": "Copilot Studio Credits",
    "per_year_cop": "Per year (25k/mo × instances)",
    "vs_subs": "Visual Studio Subscriptions",
    "ent_ide": "Enterprise IDE licenses",
    "gh_copilot": "GitHub Copilot Enterprise",
    "infra_only": "Azure credits (Infra SPD only)",
    "fin1_title": "Usage Economics",
    "fin1_sub": "Pack investment vs. retail cost of licenses your tenant currently uses — based on actual assigned licenses",
    "fin2_title": "Full Pack Value Analysis",
    "fin2_sub": "Total retail value of ALL licenses delivered by active packs vs. the cost of those packs — regardless of whether you use them",
    "pack_investment": "Pack Investment",
    "retail_used": "Retail of Licenses Used",
    "net_savings": "Net Savings / (Cost)",
    "what_retail": "What you'd pay buying used licenses at retail",
    "retail_all": "Total Retail Value of All Licenses",
    "what_all": "What all pack licenses would cost at retail",
    "gross_savings": "Gross Savings vs Retail",
    "retail_minus_packs": "Retail value minus pack investment",
    "col_line": "Line Item",
    "col_qty": "Qty",
    "col_unit_cost": "Unit Cost/yr",
    "col_annual": "Annual Amount",
    "type": "Type",
    "notes": "Notes",
    "pack_fee": "Pack Fee",
    "retail_val": "Retail Value",
    "extra_cost": "Extra Cost",
    "totals": "TOTALS (Annual)",
    "pack_investment_lbl": "pack investment",
    "retail_of_used": "retail of used",
    "retail_value": "retail value",
    "net": "net",
    "prices_title": "Edit Prices",
    "prices_intro": "<strong>Customize License Prices</strong> — All financial calculations across the app use these prices. Default values are Microsoft retail list prices (USD, annual commitment, 2025/2026). Update them to match your actual distributor prices. Changes are saved to the shared server and visible to all users.",
    "pack_fees_title": "Partner Pack Annual Fees",
    "annual_fee": "Annual fee (USD)",
    "save_prices": "💾 Save to Server",
    "reset_prices": "↺ Reset to Defaults",
    "save_confirm": "✓ Saved and synced to all users",
    "saving": "Saving...",
    "last_sync": "Last synced:",
    "sync_error": "Sync error — check connection",
    "per_user_year": "per user/year",
    "edit_usage_title": "Edit Usage Data",
    "edit_usage_intro": "Edit assigned license counts and monthly usage estimates for consumption-based services. Changes are saved and shared with all users accessing this page.",
    "assigned_lbl": "Assigned",
    "monthly_usage_lbl": "Monthly usage (USD/mo)",
    "save_usage": "💾 Save Usage Data",
    "reset_confirm": "Reset all prices to Microsoft retail defaults?",
    "off": "(off)",
    "footer_note": "For internal use only · Not for resale · Prices indicative · Shared data synced via server",
    "auto_save": "Auto-saving...",
    "saved_ok": "✓ Saved",
    "expected_monthly": "Expected usage/mo",
    "col_expected": "Expected/mo",
    "tab_backup": "Backup & Restore",
    "bk_title": "Backup & Restore",
    "bk_intro": "Automatic snapshots are taken whenever data changes on a new day, week, month, or year. You can preview and restore any snapshot below.",
    "bk_schedule": "Snapshot Schedule",
    "bk_sched_detail": "7 daily · 4 weekly · 36 monthly · 5 yearly",
    "bk_list_title": "Available Snapshots",
    "bk_slot": "Slot",
    "bk_type": "Type",
    "bk_created": "Created",
    "bk_version": "Version",
    "bk_by": "Saved By",
    "bk_actions": "Actions",
    "bk_preview": "Preview",
    "bk_restore": "Restore",
    "bk_restore_confirm": "Restore this snapshot? All current data will be replaced.",
    "bk_restored_ok": "✓ Snapshot restored successfully",
    "bk_no_snaps": "No snapshots yet. They are created automatically when data changes.",
    "bk_preview_title": "Snapshot Preview",
    "bk_close": "Close",
    "bk_do_restore": "Restore This Snapshot",
    "bk_loading": "Loading snapshots...",
    "bk_daily": "Daily",
    "bk_weekly": "Weekly",
    "bk_monthly": "Monthly",
    "bk_yearly": "Yearly",
    "bk_audit_title": "Recent Changes",
    "bk_audit_ts": "Time",
    "bk_audit_ip": "User IP",
    "bk_audit_action": "Action",
    "bk_audit_keys": "Changed",
    "bk_audit_ver": "Version",
    "conflict_title": "Data Conflict",
    "conflict_msg": "Another user saved newer data while you had the page open. Your change was not applied. The latest data has been loaded — please review and re-save if needed.",
    "conflict_ok": "OK, got it",
    "auto_refresh": "Auto-refreshing every 2 min",
    "refreshed": "Data refreshed",
    "grp_spd": "Solutions Partner designations",
    "grp_spec": "Specializations",
    "avd_included": "Included with SPD",
    "pack_total_lbl": "Total annual investment:",
    "mw_name": "Modern Work",
    "sec_name": "Security",
    "avd_name": "Azure Virtual Desktop",
    "add_lic_btn": "Add Consumption",
    "add_lic_title": "Add Consumption / Licenses",
    "add_lic_intro": "Add any license you use that wasn't in your CSV export. Pick from pack licenses (pack columns auto-fill) or enter a custom one.",
    "add_lic_from_pack": "From Pack Catalog",
    "add_lic_custom": "Custom / Manual Entry",
    "add_lic_select": "Select a license from the pack...",
    "add_lic_name": "Product name",
    "add_lic_qty": "Qty in use",
    "add_lic_type": "License type",
    "add_lic_coverage": "Coverage status",
    "add_lic_cpu": "Cost per unit / year (USD)",
    "add_lic_cancel": "Cancel",
    "add_lic_add": "Add to Tracker",
    "add_lic_remove": "Remove",
    "add_lic_remove_confirm": "Remove this manually added license?",
    "add_lic_custom_badge": "MANUAL",
    "add_lic_note": "Manually added",
    "rep_header": "Pack Replacement Sources",
    "rep_add_source": "+ Add source",
    "rep_source_lbl": "Pack license covering this",
    "rep_qty_lbl": "Users covered",
    "rep_uncovered": "uncovered — needs purchase",
    "rep_covered_by": "covered by pack",
    "rep_partial": "partially covered",
    "tab_purchase": "Needs Purchase",
    "pur_title": "What Needs to Be Purchased",
    "pur_intro": "Based on your assigned quantities and configured pack replacements, the following licenses still require separate purchase.",
    "pur_col_lic": "License",
    "pur_col_assigned": "Assigned",
    "pur_col_covered": "Covered by Pack",
    "pur_col_missing": "Still to Purchase",
    "pur_col_cpu": "Unit Cost/yr",
    "pur_col_total": "Annual Cost",
    "pur_col_source": "Pack Source",
    "pur_nothing": "Nothing to purchase — all assigned licenses are fully covered by active packs.",
    "pur_total": "Total annual purchase cost:",
    "add_lic_azure_tab": "Azure Consumption",
    "add_lic_azure_intro": "Set your expected Azure monthly spend. This is used in financial calculations to measure usage against your Azure credit entitlement.",
    "add_lic_azure_monthly": "Expected monthly Azure spend (USD)",
    "add_lic_azure_hint": "Enter your average monthly Azure consumption in USD. The pack provides credits — this tracks how much you actually use.",
    "add_lic_replace_tab": "License Replacement",
    "add_lic_replace_intro": "Map a license you currently buy to a pack license that covers it. Updates coverage status and financial calculations.",
    "add_lic_replace_from_lbl": "License being replaced (currently paying for)",
    "add_lic_replace_to_lbl": "Pack license that replaces it",
    "add_lic_replace_qty_lbl": "Quantity being replaced",
    "add_lic_replace_select_from": "Select license to replace...",
    "add_lic_replace_select_to": "Select pack replacement...",
    "add_lic_replace_btn": "Apply Replacement",
    "add_lic_replace_note": "Replaced by pack",
    "add_lic_replace_remove": "Remove replacement",
    "add_lic_replace_confirm_msg": "Remove this license replacement?"
  },
  "es": {
    "app_title": "Beneficios de Partner Microsoft 2026 — Seguimiento de Licencias y Finanzas",
    "app_sub": "Guía de Beneficios 18 Feb 2026 · sgx-labs.com/partners/microsoft",
    "tag_ms": "Microsoft AI Cloud Partner Program",
    "tag_date": "Feb 2026",
    "tab_licenses": "Licencias",
    "tab_usage": "Uso vs Pack",
    "tab_all": "Todas las Licencias",
    "tab_cloud": "Créditos y Derechos Cloud",
    "client_select_title": "Seleccionar Cliente",
    "client_new": "Nuevo Cliente",
    "client_name_placeholder": "Nombre del cliente…",
    "client_create": "Crear",
    "client_back": "← Clientes",
    "lic_title": "Licencias del Tenant",
    "lic_add": "Agregar Licencia",
    "lic_import_csv": "Importar CSV",
    "lic_col_name": "Producto",
    "lic_col_sku": "SKU",
    "lic_col_total": "Total",
    "lic_col_assigned": "Asignadas",
    "lic_col_price": "Precio (USD/mes)",
    "lic_col_actions": "",
    "lic_fetch_prices": "Obtener precios",
    "lic_csv_hint": "Pegar CSV con columnas: Nombre del Producto, Total, Expiradas, Asignadas",
    "lic_csv_import_btn": "Importar",
    "lic_csv_cancel": "Cancelar",
    "lic_save": "Guardar",
    "lic_delete_confirm": "¿Eliminar esta licencia?",
    "tab_fin1": "Economía de Uso",
    "tab_fin2": "Valor Total del Pack",
    "tab_prices": "Editar Precios",
    "pack_bar_label": "Packs activos y multiplicadores",
    "year": "/ año",
    "instances": "instancias",
    "launch_name": "Partner Launch",
    "core_name": "Success Core",
    "exp_name": "Success Expanded",
    "infra_name": "Solutions Partner: Infraestructura",
    "cov_legend": "Cobertura:",
    "leg_covered": "Cubierto",
    "leg_upgrade": "Actualización disponible",
    "leg_needs": "Requiere compra",
    "leg_free": "Gratis / Trial",
    "show": "Ver",
    "all": "Todos",
    "covered": "Cubiertos",
    "upgrades": "Actualizaciones",
    "not_covered": "Sin Cobertura",
    "free_trial": "Gratis/Trial",
    "sort": "Orden",
    "by_coverage": "Por Cobertura",
    "by_name": "Por Nombre",
    "most_assigned": "Más Asignados",
    "most_needed": "Más Necesarios",
    "highest_cost": "Mayor Costo",
    "stat_skus": "SKUs en Tenant",
    "stat_assigned": "Total Asignados",
    "stat_covered": "Cubiertos",
    "stat_upgrades": "Actualizaciones",
    "stat_needs": "Requieren Compra",
    "stat_over": "Sobre el Límite",
    "col_product": "Producto del Tenant",
    "col_total": "Total",
    "col_assigned": "Asignados",
    "col_avail": "Total Disponible",
    "col_usage": "Uso vs Pack",
    "col_needed": "Lic. Necesarias",
    "col_cost": "Costo/Unidad/año",
    "col_coverage": "Cobertura",
    "col_edit": "Editar",
    "pill_covered": "Cubierto",
    "pill_upgrade": "Actualización",
    "pill_needs": "Requiere Compra",
    "pill_free": "Gratis/Trial",
    "pill_over": "Sobre Límite",
    "sec_covered": "✓  Cubierto por los packs activos",
    "sec_upgrade": "↑  El pack incluye una edición superior",
    "sec_uncovered": "✕  Sin cobertura — requiere compra separada",
    "sec_free": "◦  Licencias gratuitas / de prueba",
    "no_pack_limit": "sin límite de pack",
    "tab_all_title": "Todas las Licencias del Pack",
    "pack_filter": "Pack",
    "category_filter": "Categoría",
    "new_in": "Nuevo en",
    "all_cats": "Todas las Categorías",
    "col_license": "Licencia / Producto",
    "col_category": "Categoría",
    "col_type": "Tipo",
    "col_best_qty": "Mejor Cant.",
    "col_retail": "Valor Retail/año",
    "col_new": "Nuevo",
    "stat_pack_lic": "Licencias del Pack",
    "stat_retail": "Valor Retail Total/año",
    "stat_invest": "Inversión en Packs/año",
    "stat_savings": "Ahorro Bruto/año",
    "cloud_title": "Servicios Cloud, Créditos y Derechos de IA",
    "cloud_intro": "<strong>Servicios Cloud, Créditos y Derechos de IA</strong> — Todos los derechos cloud, créditos Azure, presupuestos de servicios de IA y derechos de desarrollo incluidos en sus packs activos. Los valores muestran el total combinado entre todas las instancias de packs activos.",
    "combined_cloud": "Derechos Cloud Combinados de Todos los Packs Activos",
    "azure_credits": "Créditos de Producción Azure",
    "per_year": "Por año en packs activos",
    "copilot_credits": "Créditos Copilot Studio",
    "per_year_cop": "Por año (25k/mes × instancias)",
    "vs_subs": "Suscripciones Visual Studio",
    "ent_ide": "Licencias Visual Studio Enterprise",
    "gh_copilot": "GitHub Copilot Enterprise",
    "infra_only": "Créditos Azure (solo Infra SPD)",
    "fin1_title": "Economía de Uso",
    "fin1_sub": "Inversión en packs vs. costo retail de licencias que su tenant usa actualmente — basado en licencias asignadas reales",
    "fin2_title": "Análisis del Valor Total del Pack",
    "fin2_sub": "Valor retail total de TODAS las licencias entregadas por packs activos vs. el costo de esos packs — independientemente de si las usa",
    "pack_investment": "Inversión en Packs",
    "retail_used": "Retail de Licencias Usadas",
    "net_savings": "Ahorro Neto / (Costo)",
    "what_retail": "Lo que pagaría comprando las licencias usadas a precio retail",
    "retail_all": "Valor Retail Total de Todas las Licencias",
    "what_all": "Lo que costarían todas las licencias del pack a precio retail",
    "gross_savings": "Ahorro Bruto vs Retail",
    "retail_minus_packs": "Valor retail menos inversión en packs",
    "col_line": "Línea",
    "col_qty": "Cant.",
    "col_unit_cost": "Costo Unit./año",
    "col_annual": "Monto Anual",
    "type": "Tipo",
    "notes": "Notas",
    "pack_fee": "Cuota Pack",
    "retail_val": "Valor Retail",
    "extra_cost": "Costo Extra",
    "totals": "TOTALES (Anual)",
    "pack_investment_lbl": "inversión en packs",
    "retail_of_used": "retail de uso",
    "retail_value": "valor retail",
    "net": "neto",
    "prices_title": "Editar Precios",
    "prices_intro": "<strong>Personalizar Precios de Licencias</strong> — Todos los cálculos financieros de la app usan estos precios. Los valores por defecto son los precios de lista retail de Microsoft (USD, compromiso anual, 2025/2026). Actualícelos para reflejar los precios reales de su distribuidor. Los cambios se guardan en el servidor y son visibles para todos los usuarios.",
    "pack_fees_title": "Cuotas Anuales de Packs",
    "annual_fee": "Cuota anual (USD)",
    "save_prices": "💾 Guardar en Servidor",
    "reset_prices": "↺ Restaurar Valores por Defecto",
    "save_confirm": "✓ Guardado y sincronizado con todos los usuarios",
    "saving": "Guardando...",
    "last_sync": "Última sincronización:",
    "sync_error": "Error de sincronización — verificar conexión",
    "per_user_year": "por usuario/año",
    "edit_usage_title": "Editar Datos de Uso",
    "edit_usage_intro": "Edite las cantidades de licencias asignadas y las estimaciones de uso mensual para servicios de consumo. Los cambios se guardan y comparten con todos los usuarios.",
    "assigned_lbl": "Asignados",
    "monthly_usage_lbl": "Uso mensual (USD/mes)",
    "save_usage": "💾 Guardar Datos de Uso",
    "reset_confirm": "¿Restaurar todos los precios a los valores retail de Microsoft?",
    "off": "(inactivo)",
    "footer_note": "Solo para uso interno · No para reventa · Precios indicativos · Datos compartidos sincronizados vía servidor",
    "auto_save": "Guardando automáticamente...",
    "saved_ok": "✓ Guardado",
    "expected_monthly": "Uso esperado/mes",
    "col_expected": "Esperado/mes",
    "tab_backup": "Respaldos",
    "bk_title": "Respaldo y Restauración",
    "bk_intro": "Se toman instantáneas automáticas cada vez que los datos cambian en un día, semana, mes o año nuevos. Puede previsualizar y restaurar cualquier instantánea.",
    "bk_schedule": "Programa de Instantáneas",
    "bk_sched_detail": "7 diarias · 4 semanales · 36 mensuales · 5 anuales",
    "bk_list_title": "Instantáneas Disponibles",
    "bk_slot": "Slot",
    "bk_type": "Tipo",
    "bk_created": "Creado",
    "bk_version": "Versión",
    "bk_by": "Guardado por",
    "bk_actions": "Acciones",
    "bk_preview": "Vista Previa",
    "bk_restore": "Restaurar",
    "bk_restore_confirm": "¿Restaurar esta instantánea? Todos los datos actuales serán reemplazados.",
    "bk_restored_ok": "✓ Instantánea restaurada exitosamente",
    "bk_no_snaps": "Sin instantáneas aún. Se crean automáticamente cuando los datos cambian.",
    "bk_preview_title": "Vista Previa de Instantánea",
    "bk_close": "Cerrar",
    "bk_do_restore": "Restaurar Esta Instantánea",
    "bk_loading": "Cargando instantáneas...",
    "bk_daily": "Diaria",
    "bk_weekly": "Semanal",
    "bk_monthly": "Mensual",
    "bk_yearly": "Anual",
    "bk_audit_title": "Cambios Recientes",
    "bk_audit_ts": "Hora",
    "bk_audit_ip": "IP Usuario",
    "bk_audit_action": "Acción",
    "bk_audit_keys": "Modificado",
    "bk_audit_ver": "Versión",
    "conflict_title": "Conflicto de Datos",
    "conflict_msg": "Otro usuario guardó datos más recientes mientras tenía la página abierta. Su cambio no fue aplicado. Se cargaron los datos más recientes — revise y vuelva a guardar si es necesario.",
    "conflict_ok": "Entendido",
    "auto_refresh": "Actualización automática cada 2 min",
    "refreshed": "Datos actualizados",
    "grp_spd": "Designaciones Solutions Partner",
    "grp_spec": "Especializaciones",
    "avd_included": "Incluido con SPD",
    "pack_total_lbl": "Inversión anual total:",
    "mw_name": "Modern Work",
    "sec_name": "Security",
    "avd_name": "Azure Virtual Desktop",
    "add_lic_btn": "Agregar Consumo",
    "add_lic_title": "Agregar Consumo / Licencias",
    "add_lic_intro": "Agregue cualquier licencia que use y que no estaba en su exportación CSV. Elija del catálogo de packs (las columnas de pack se rellenan solas) o ingrese una entrada personalizada.",
    "add_lic_from_pack": "Del Catálogo de Packs",
    "add_lic_custom": "Entrada Personalizada / Manual",
    "add_lic_select": "Seleccione una licencia del pack...",
    "add_lic_name": "Nombre del producto",
    "add_lic_qty": "Cantidad en uso",
    "add_lic_type": "Tipo de licencia",
    "add_lic_coverage": "Estado de cobertura",
    "add_lic_cpu": "Costo por unidad / año (USD)",
    "add_lic_cancel": "Cancelar",
    "add_lic_add": "Agregar al Seguimiento",
    "add_lic_remove": "Eliminar",
    "add_lic_remove_confirm": "¿Eliminar esta licencia agregada manualmente?",
    "add_lic_custom_badge": "MANUAL",
    "add_lic_note": "Agregada manualmente",
    "rep_header": "Fuentes de Reemplazo del Pack",
    "rep_add_source": "+ Agregar fuente",
    "rep_source_lbl": "Licencia del pack que cubre esto",
    "rep_qty_lbl": "Usuarios cubiertos",
    "rep_uncovered": "sin cobertura — requiere compra",
    "rep_covered_by": "cubierto por pack",
    "rep_partial": "parcialmente cubierto",
    "tab_purchase": "Requiere Compra",
    "pur_title": "Qué Debe Comprarse",
    "pur_intro": "Según las cantidades asignadas y los reemplazos de pack configurados, las siguientes licencias aún requieren compra separada.",
    "pur_col_lic": "Licencia",
    "pur_col_assigned": "Asignados",
    "pur_col_covered": "Cubierto por Pack",
    "pur_col_missing": "Aún por Comprar",
    "pur_col_cpu": "Costo Unit./año",
    "pur_col_total": "Costo Anual",
    "pur_col_source": "Fuente del Pack",
    "pur_nothing": "Nada que comprar — todas las licencias asignadas están cubiertas por packs activos.",
    "pur_total": "Costo anual total de compra:",
    "add_lic_azure_tab": "Consumo Azure",
    "add_lic_azure_intro": "Configure su gasto mensual esperado de Azure. Se usa en los cálculos financieros para medir el uso frente a su crédito Azure.",
    "add_lic_azure_monthly": "Gasto mensual esperado en Azure (USD)",
    "add_lic_azure_hint": "Ingrese su consumo mensual promedio de Azure en USD. El pack proporciona créditos — esto registra cuánto usa realmente.",
    "add_lic_replace_tab": "Reemplazo de Licencia",
    "add_lic_replace_intro": "Vincule una licencia que compra actualmente con la licencia del pack que la reemplaza. Actualiza el estado de cobertura y los cálculos financieros.",
    "add_lic_replace_from_lbl": "Licencia a reemplazar (actualmente pagando)",
    "add_lic_replace_to_lbl": "Licencia del pack que la reemplaza",
    "add_lic_replace_qty_lbl": "Cantidad a reemplazar",
    "add_lic_replace_select_from": "Seleccione la licencia a reemplazar...",
    "add_lic_replace_select_to": "Seleccione el reemplazo del pack...",
    "add_lic_replace_btn": "Aplicar Reemplazo",
    "add_lic_replace_note": "Reemplazada por pack",
    "add_lic_replace_remove": "Eliminar reemplazo",
    "add_lic_replace_confirm_msg": "¿Eliminar este reemplazo de licencia?"
  }
};
